apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdi-svc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdi-svc-deployment
  template:
    metadata:
      labels:
        app: mdi-svc-deployment
    spec:
      containers:
      - name: mdi-svc-deployment
        image: dtfernando/mdi_standalone_flask:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - containerPort: 5002
      nodeName: standalone-worker1